// <auto-generated />
using ETProject.api.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ETProject.api.Migrations
{
    [DbContext(typeof(ETDbContext))]
    [Migration("20200508160528_DropTableCategories4")]
    partial class DropTableCategories4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");
#pragma warning restore 612, 618
        }
    }
}
